### ISSUE TITLE
Way to increase time out period?

### ISSUE THREAD

**Issue by paultannenbaum** [gushonorato/mechanizex#32]
Hi again @gushonorato 

So far the library has been very useful for my needs, thanks again for making this! One of the sites I am crawling has very slow response times. Is there a way to increase the time limit before `Mechanize` exits with a time out?

**Comment by gushonorato** [comment]
Hello @paultannenbaum. Unfortunately, some "low level" features of the HTTP protocol are not implemented yet. I've reserved the `opts` param on the `request!` function (https://github.com/gushonorato/mechanize/blob/master/lib/mechanize/browser.ex#L527) to pass these lower-level options to the HTTP client adapter, but it's working in progress. I'll implement that when working on the cookies feature, probably with a rewrite on adapter API too.

Under the hood, Mechanize is using HTTPoison, which uses hackney. Have you checked if there is an option to pass these `recv_timeout` option to hackney globally (probably using something like `Application.get_env()`)?

Another way is to pass these options to hackney using `opts` param in `request!` function, as I said before. I'd love to add this feature, but I'm working on tight deadlines for the next couple weeks. If you in a hurry, you can send a pull request. I think it’s not a very complicated change to make.

**Comment by paultannenbaum** [comment]
@gushonorato Thanks for the response, I'll take a stab at it and open up a PR. Cheers!

**Comment by gushonorato** [comment]
Closed by #33
